# Generated by Django 2.2.4 on 2020-01-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Classes d'ages")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Conditions')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Auteurs des décisions')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Delits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Types de délits')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Types de diagnostics')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Echecconditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Non respect des conditionsCauses d'échec")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Echecmotifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Causes d'échec")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Echecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Conséquences en cas de non suivi du programme')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Évaluations')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Exclus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Exclusions du programme')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Fins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Achèvement du programme')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Judiciaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Étapes judiciaires')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Limites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Limites')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Partenaire')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Prérequis')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Professionnels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name=' * Professionnels')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Causes d'échec")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Références au programme')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Reunions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Réunions')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Succes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Conséquences en cas d'adhérence au programme")),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Surveillances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Surveillance')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Typetraitements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Types de traitements')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Paj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='1) * Nom du programme')),
                ('sigle', models.CharField(blank=True, max_length=250, null=True, verbose_name='1) Sigle ou acronyme du programme')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse civique du programme (point de chute)')),
                ('nomresponsable', models.CharField(blank=True, max_length=250, null=True, verbose_name='2) * Qui est la personne responsable?')),
                ('formationresponsable', models.CharField(blank=True, max_length=250, null=True, verbose_name='2) Quelle est sa formation?')),
                ('courrielresponsable', models.CharField(blank=True, max_length=250, null=True, verbose_name='2) Courriel du responsable du programme')),
                ('telresponsable', models.CharField(blank=True, max_length=250, null=True, verbose_name='2) Tel du responsable du programme')),
                ('titreresponsable', models.CharField(blank=True, max_length=250, null=True, verbose_name='2) Titre ou occupation du responsable du programme')),
                ('confidentiel', models.BooleanField(verbose_name='* Cocher si ces informations sont confidentielles')),
                ('nomrepondant', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom du répondant a questionnaire')),
                ('courrielrepondant', models.CharField(blank=True, max_length=250, null=True, verbose_name='Courriel du répondant a questionnaire')),
                ('telrepondant', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tel du répondant a questionnaire')),
                ('siteweb', models.CharField(blank=True, max_length=250, null=True, verbose_name='3) * Adresse du site web du programme')),
                ('rapportannuel', models.BooleanField(verbose_name="4) * Cocher s'il y a un rapport annuel")),
                ('tsmfile', models.FileField(blank=True, help_text="ATTENTION PAS D'ACCENT DANS LE NOM DU FICHIER", null=True, upload_to='DocsReferences', verbose_name='4a) Rapport annuel de ce programme ou de la documentation utile')),
                ('debut', models.CharField(blank=True, max_length=250, null=True, verbose_name='5) * Depuis quand ce programme existe-t-il? (mois et année si possible)')),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='6) * Objectifs du programme (résumé)')),
                ('clientele', models.TextField(blank=True, null=True, verbose_name='7) Clientèle cible du programme')),
                ('territoire', models.CharField(blank=True, max_length=250, null=True, verbose_name='1) * Quelle juridiction territoriale votre programme dessert-il?')),
                ('affiliation', models.CharField(blank=True, max_length=250, null=True, verbose_name='2) * À quel(s) tribunal/aux votre programme est-il affilié?')),
                ('etapejudiciairtxt', models.TextField(blank=True, null=True, verbose_name='8 +)Détails')),
                ('referencetxt', models.TextField(blank=True, null=True, verbose_name='9+) Détails')),
                ('prerequistexte', models.TextField(blank=True, null=True, verbose_name='10 suite) Précisions sur les critères d’admissibilité')),
                ('exclusiontexte', models.TextField(blank=True, null=True, verbose_name='11 suite) Détails')),
                ('decisionpouvoir', models.TextField(blank=True, null=True, verbose_name='12+) Comment la décision est-elle prise?')),
                ('delais', models.CharField(blank=True, max_length=250, null=True, verbose_name='13) Quels sont les délais d’attente après avoir inscrit une demande?')),
                ('traitementtexte', models.TextField(blank=True, null=True, verbose_name='14a) Détails sur les services offerts aux participants')),
                ('conditiontexte', models.TextField(blank=True, null=True, verbose_name='15a) Détails des conditions')),
                ('respectcondition', models.BooleanField(verbose_name='16) Est-ce que le respect des conditions indiquées à la question 15 mène à la réussite du programme?')),
                ('reussitedef', models.TextField(blank=True, null=True, verbose_name='16b) Si non, qu’est-ce qui entraîne la réussite du programme?')),
                ('echecconditiontexte', models.TextField(blank=True, null=True, verbose_name='17a) Non respects détails')),
                ('echectexte', models.TextField(blank=True, null=True, verbose_name='17--a) Précisions sur les motifs d’échec')),
                ('succestexte', models.TextField(blank=True, null=True, verbose_name='18a) Succès détails')),
                ('finbool', models.BooleanField(verbose_name='19) À la fin du programme, faites-vous une transition vers un suivi en communauté?')),
                ('fintexte', models.TextField(blank=True, null=True, verbose_name='19a) Si oui\xa0: comment assurez-vous la transition vers ce suivi?')),
                ('progdureebool', models.BooleanField(verbose_name='20) La participation au programme est-elle d’une durée prédéterminée?')),
                ('traitementduree', models.CharField(blank=True, max_length=250, null=True, verbose_name='20a) Si oui: quelle est-elle?')),
                ('traitementmin', models.CharField(blank=True, max_length=250, null=True, verbose_name='20b) Durée maximale')),
                ('traitementmax', models.CharField(blank=True, max_length=250, null=True, verbose_name='20b) Durée minimale')),
                ('autreprogramme', models.BooleanField(verbose_name='21) Y a-t-il d’autres programmes proposant des alternatives à l’incarcération ou\xa0à la judiciarisation dans votre juridiction?')),
                ('autreprogramtexte', models.TextField(blank=True, null=True, verbose_name='21a) Si oui\xa0: lesquels?')),
                ('autreaffilie', models.BooleanField(verbose_name='21b) Sont-ils affiliés à votre programme?')),
                ('partenariattexte', models.TextField(blank=True, null=True, verbose_name='22a) Si oui\xa0:  précisions sur les partenariats')),
                ('caseload', models.CharField(blank=True, max_length=250, null=True, verbose_name='P3- Nombre de dossier à charge de l’intervenant-pivot ou agent de liaison')),
                ('limiteparticipants', models.BooleanField(verbose_name='S1- Avez-vous une limite de participants?')),
                ('limitenb', models.TextField(blank=True, null=True, verbose_name='S1a- Si oui, à combien est établie la limite actuelle ?')),
                ('partactif', models.CharField(blank=True, default=0, max_length=250, null=True, verbose_name='S2- Combien avez-vous de participants actifs actuellement?')),
                ('autrejur', models.BooleanField(verbose_name='S3- Recevez-vous des participants d’autres juridictions?')),
                ('autrejurtext', models.TextField(blank=True, null=True, verbose_name='S3a- Si oui: dans quelles circonstances?')),
                ('partmoyen', models.IntegerField(blank=True, default=0, null=True, verbose_name='S4- En moyenne, combien de nouveaux participants intègrent le programme chaque mois?')),
                ('nbreussi', models.IntegerField(blank=True, default=0, null=True, verbose_name='S5a- Combien de participants ont complété le programme dans la dernière année?')),
                ('nbechoue', models.IntegerField(blank=True, default=0, null=True, verbose_name='S5b- Combien de participants ont échoué au programme dans la dernière année?')),
                ('nbsuccesdebut', models.IntegerField(blank=True, default=0, null=True, verbose_name='S5c- Nombre de participants ayant achevé le programme avec succès depuis son entrée en opération?')),
                ('nbechouedebut', models.IntegerField(blank=True, default=0, null=True, verbose_name='S5d- Nombre de participants ayant échoué depuis l’entrée en opération du programme (incluant les retraits volontaires)')),
                ('evaluation', models.BooleanField(verbose_name='4) * Votre programme a-t-il déjà fait l’objet d’une évaluation?')),
                ('evalquand', models.CharField(blank=True, max_length=250, null=True, verbose_name='4a) Quand est-ce que cette évaluation a eu lieu?')),
                ('evalqui', models.CharField(blank=True, max_length=250, null=True, verbose_name='4c) Par qui cette évaluation a-t-elle été réalisée?')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='4d) Quels sont les résultats de cette évaluation?')),
                ('evaluationfuture', models.BooleanField(verbose_name=' * (si non évalué) Une évaluation du programme est-elle prévue?')),
                ('evafuturedetail', models.TextField(blank=True, null=True, verbose_name='(si prévue) Quand, quel type et par qui le programme sera évalué?')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pajsm.Ages', verbose_name="10+) Quels sont les critères d'age?")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('condition', models.ManyToManyField(default='1', to='pajsm.Conditions', verbose_name='15) * Quelles sont les conditions à respecter une fois dans le programme?')),
                ('decision', models.ManyToManyField(default='1', to='pajsm.Decisions', verbose_name='12) Qui a un pouvoir décisionnel sur l’admission au programme')),
                ('echeccondition', models.ManyToManyField(default='1', to='pajsm.Echecconditions', verbose_name='17) * Quelles conséquences s’appliquent en cas de non-respect des conditions?')),
                ('echecmotif', models.ManyToManyField(to='pajsm.Echecmotifs', verbose_name="S6- Quels sont les motifs les plus fréquents d'échec du programme?")),
                ('etapejudiciaire', models.ManyToManyField(default='1', to='pajsm.Judiciaires', verbose_name='8) * À quelle étape du processus judiciaire les participants sont-ils référés au programme?')),
                ('evaltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pajsm.Evaluations', verbose_name='4b) Quel type était-ce? ')),
                ('exclusions', models.ManyToManyField(default='1', to='pajsm.Exclus', verbose_name='11) * Quels sont les critères d’exclusion?')),
                ('partenariat', models.ManyToManyField(default='1', to='pajsm.Partenaires', verbose_name='22) Avez-vous établi des partenariats avec d’autres services ou organisations?')),
                ('prerequis', models.ManyToManyField(default='1', to='pajsm.Prerequis', verbose_name='10) * Quels sont les critères d’admissibilité?')),
                ('public', models.ManyToManyField(to='pajsm.Public', verbose_name='* Autorisation à rendre public les coordonnées de la personne responsable (sur le site Web de l’Osbervatoire ?)')),
                ('reference', models.ManyToManyField(default='1', to='pajsm.References', verbose_name='9) * De qui proviennent les références de vos participants à ce programme?')),
                ('succes', models.ManyToManyField(default='1', to='pajsm.Succes', verbose_name='18) * Qu’arrive-t-il lorsque le programme est complété avec succès?')),
                ('traitementtype', models.ManyToManyField(default='1', to='pajsm.Typetraitements', verbose_name='14) * Quels sont les services offerts aux participants?')),
                ('typedelits', models.ManyToManyField(default='1', to='pajsm.Delits', verbose_name="10+) Types de délits ou d'accusations acceptés")),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(default=0)),
                ('duree', models.CharField(blank=True, max_length=250, null=True, verbose_name='Temps de travail')),
                ('tache', models.TextField(blank=True, null=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pajsm.Professionnels', verbose_name='* Professionnels')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pajsm.Paj')),
            ],
            options={
                'ordering': ['tribunal', 'nombre'],
            },
        ),
    ]
