# Generated by Django 2.2.4 on 2020-01-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pajsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paj',
            name='audiencefreq',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rféquence des audiences'),
        ),
        migrations.AddField(
            model_name='paj',
            name='reunionfreq',
            field=models.TextField(blank=True, null=True, verbose_name='Fréquence des réunions de l’équipe'),
        ),
    ]
