# Generated by Django 2.2.4 on 2020-01-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pajsm', '0003_auto_20200107_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentation',
            field=models.FileField(help_text="ATTENTION PAS D'ACCENT DANS LE NOM DES FICHIERS", upload_to='DocsReferences', verbose_name="ATTENTION PAS D'ACCENT DANS LE NOM DES FICHIERS"),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifhistoire', models.TextField(verbose_name='Description des modifications importantes')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pajsm.Paj')),
            ],
        ),
    ]
